spring.application.name=ShiftTracker

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

# Postgres database
# obrisati username i password prije pushanja na github ili staviti u git ignore
spring.datasource.url=jdbc:postgresql://localhost:5432/shifttracker
spring.datasource.username=your_username
spring.datasource.password=your_password



# update - da se baza azurira kako dodajemo entitete -- moze biti problem
# create - ponovo kreira tablice pri svakom pokretanju aplikacije -- tabloice se brisu i ponovo kreiraju i bez podataka
# ceate-drop - ne koristimo
# validate - ne koristimo
# node - bez automatskog pokretanja sheme - baza se ne krira prilikom pokretanja -- kad idemo u produkciju
spring.jpa.hibernate.ddl-auto=update



spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

#da se izbirse baza prije pokretanja
#spring.jpa.hibernate.ddl-auto=create


