spring.application.name=ShiftTracker

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

# H2 database
spring.datasource.url=jdbc:h2:file:./testdb

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

#da se izbirse baza prije pokretanja
#spring.jpa.hibernate.ddl-auto=create


