spring.application.name=ShiftTracker

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

# Postgres local
#spring.datasource.url=jdbc:postgresql://localhost:5432/shifttracker
#spring.datasource.username=postgres
#spring.datasource.password=postgrespass

# Postgres Railway
spring.datasource.url=jdbc:postgresql://viaduct.proxy.rlwy.net:59783/railway
spring.datasource.username=postgres
spring.datasource.password=dProMhivBMNSlbeDueqgNtspwPJCaNZl

# Hibernate Dialect for PostgreSQL
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true



